# Site settings
title: Loïc Renaud Portfolio
description: Welcome to my portfolio, you can find out some of my projects
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Loïc Renaud
user_description: Eventhough I have finished school, I love to learn. I keep learning new things everyday, and that is what made me passionate about computer sciences. I really enjoy working on challenging IT project and trying to figure out what might be the best solution to a given problem.I do not affiliate my self to a specific programming language, in my opinion the language is just a tool and we have a huge tool-box at our disposal to solve different kind of problems. However I do love using cutting-edge technologies.
user_title: Software Developer
email: loic@renaud.com
twitter_username: lorem_ipsum
github_username:  llccrr
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
