# Site settings
title: Loïc Renaud Portfolio
description: Welcome to my portfolio, you can find out some of my projects
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Loïc Renaud
user_description: All Hail Recursion
user_title: Software Developer
email: loic@renaud.com
twitter_username: lorem_ipsum
github_username:  llccrr
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
